### PR TITLE
Add to Graph control arrow directions which represent the direction of the link between two nodes

### PR DESCRIPTION
**Pull request by ido-ran**
Hi,
After long time I finally manage to put our code into pull request.
In our application we use your graph control to allow navigation inside a network. Each node in the graph represent either a node or link in the network. Between nodes in the graph that represent link we like to present the direction of the link.
This is where AroowDirectionType come into play. Each ViewModel in our application know to answer the question "What is your direction relative to the center?".
In the demo application I simply randomize a value, but it's just for demo purposes.

If you think the code is not good enough, better naming or documentation please let me know.

Thank you,
Ido.

### CODE REVIEW

**Comment by kevmoo** [comment]
Excited to get the pull request. Initial thoughts:
1. Please stay consistent with the ordering of elements in the code. Group properties, etc, with others.
2. The [To|From]ElementGradient properties are private and only assigned once. Just use the line color
3. The triangle geometry is never changed. Define it once, freeze it, reuse it
4. There should be a ctor param for arrow direction in NodeClass
5. Rename `ArrowDirectionType` to `GraphArrowDirection`. Put it in its own file.

**Comment by kevmoo** [comment]
Also, your pull request includes white-change-only changes to unrelated parts of Graph.cs. Remove these. A whitespace clean-up commit is great, too, but it should be separate.

**Comment by ido-ran** [comment]
We will make the fixes and resubmit. Thanks

**Comment by ido-ran** [comment]
long delay - I will get to it

**Comment by kevmoo** [comment]
Closing until I get your new patch. No hurry. :-)

**Pull request closed without merging**
